name: Crystal CI

on: push

jobs:
  test:
    name: Specs
    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal:1.0.0-alpine

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: shards install

      - name: Run specs
        run: crystal spec

      - name: Check file formatting
        run: crystal tool format --check src spec
        if: always()
